/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.1
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Ignore
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    
    /**
     * 搜索用户
     *
     * 获取用户详细信息
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usersGetTest() throws ApiException {
        String id = null;
        Object response = api.usersGet(id);

        // TODO: test validations
    }
    
    /**
     * 添加用户
     *
     * 创建一个新的用户
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usersPostTest() throws ApiException {
        api.usersPost();

        // TODO: test validations
    }
    
}
