/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object UsersApi {

  /**
   * 获取用户详细信息
   * 
   * Expected answers:
   *   code 200 : Any (OK)
   * 
   * @param id 用户逐渐
   */
  def usersGet(id: Option[String] = None): ApiRequest[Any] =
    ApiRequest[Any](ApiMethods.GET, "https://virtserver.swaggerhub.com/coolazrael/test/1.0.0", "/users", "application/json")
      .withQueryParam("id", id)
      .withSuccessResponse[Any](200)
        /**
   * 创建一个新的用户
   * 
   * Expected answers:
   *   code 200 :  (OK)
   */
  def usersPost(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/coolazrael/test/1.0.0", "/users", "application/json")
      .withSuccessResponse[Unit](200)
      

}

